host    = ${application.host}
port    = ${application.port}
name    = ${project.artifactId}
version = ${project.version}
commit  = ${git.commit.id}

database.url      = ${database.url}
database.username = ${database.username}
database.password = ${database.password}
