application.host = 0.0.0.0
application.port = ${PORT}

database.url      = ${DATABASE_URL}
database.username = ${DATABASE_USERNAME}
database.password = ${DATABASE_PASSWORD}

docker.image.base = gcr.io/distroless/base-nossl-debian12

logger.root.level = INFO
logger.app.level  = INFO

functional-tests.server='http://${project.artifactId}:${application.port}/api/v1'
functional-tests.root-server='http://${project.artifactId}:${application.port}'
